version: 2.1

jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.1.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

  audit:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.1.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm audit

# workflows:
#   version: 2
#   nightly:
#       triggers:
#         - schedule:
#             cron: "0 4 * * 2"
#             filters:
#               branches:
#                 only:
#                   - master
#       jobs:
#         - audit